-- Migration: Reformat product descriptions into one consistent HTML template
-- and refine allergen tags for all 56 existing Gau Bakery products (ids 2-53
-- rewritten from source marketing copy, ids 54-73 aligned to the template
-- already used by the newer catalog additions).
-- Run AFTER 2026_07_26_ai_features.sql (which adds the co_* columns); the tag
-- values here supersede that migration's initial tags.
-- Date: 2026-07-26

-- === Reformatted descriptions ===

UPDATE banh SET mo_ta='<p><strong>Mô tả sản phẩm:</strong> Bánh kem Chocolate dành cho tín đồ mê vị đậm đà, nồng nàn. Cốt bánh bông lan cacao xốp mềm quyện cùng lớp kem chocolate béo ngậy, tan ngay đầu lưỡi. Bề mặt phủ ganache chocolate bóng mượt, ngọt thanh xen chút đắng nhẹ tinh tế.</p><p><strong>Thành phần:</strong> Bột mì, trứng, bột cacao, kem tươi, chocolate, đường, bơ.</p><p><strong>Bảo quản:</strong> Ngăn mát tủ lạnh 2-8°C, dùng trong 3-5 ngày.</p>' WHERE id=2;
UPDATE banh SET mo_ta='<p><strong>Mô tả sản phẩm:</strong> Bánh kem Cherry là sự kết hợp sang trọng giữa cốt bánh bông lan mềm mại và lớp kem tươi thanh khiết, điểm xuyết cherry đỏ mọng ngọt lịm. Vị chua nhẹ của cherry hòa quyện độ béo của kem phô mai tạo hương vị tinh tế, không ngấy. Bề mặt trang trí cherry nguyên cuống tươi ngon, đẳng cấp.</p><p><strong>Thành phần:</strong> Bột mì, trứng, kem tươi, phô mai kem, cherry tươi, đường.</p><p><strong>Bảo quản:</strong> Ngăn mát tủ lạnh 2-8°C, dùng trong 3-5 ngày.</p>' WHERE id=3;
UPDATE banh SET mo_ta='<p><strong>Mô tả sản phẩm:</strong> Bánh mì bơ tỏi có lớp vỏ ngoài vàng giòn, phủ đều hỗn hợp bơ tỏi thơm lừng. Bơ tan chảy thấm vào từng thớ bánh, hòa quyện vị tỏi đậm đà và rau thơm. Kết cấu giòn nhẹ bên ngoài, mềm bên trong, thích hợp ăn vặt hoặc ăn sáng.</p><p><strong>Thành phần:</strong> Bột mì, bơ, tỏi, men nở, rau thơm, muối.</p><p><strong>Bảo quản:</strong> Nơi khô ráo thoáng mát trong ngày, có thể để ngăn mát tủ lạnh nếu chưa dùng ngay, hâm nóng lại trước khi ăn.</p>' WHERE id=13;
UPDATE banh SET mo_ta='<p><strong>Mô tả sản phẩm:</strong> Bánh bông lan trứng muối hòa quyện vị ngọt mềm của cốt bánh bông lan và vị mặn béo của trứng muối. Lớp bánh xốp nhẹ phủ sốt bơ béo ngậy, chà bông tơi xốp và trứng muối bùi béo. Tổng thể hương vị mặn ngọt hài hòa, kích thích vị giác.</p><p><strong>Thành phần:</strong> Bột mì, trứng, trứng muối, chà bông, sốt bơ, đường.</p><p><strong>Bảo quản:</strong> Ngăn mát tủ lạnh 2-8°C, dùng trong 3-5 ngày.</p>' WHERE id=14;
UPDATE banh SET mo_ta='<p><strong>Mô tả sản phẩm:</strong> Bánh mì Hotdog có lớp vỏ mềm mịn, thơm nhẹ mùi bơ và phần xúc xích đậm đà bên trong. Xúc xích chín tới, dai ngon, kết hợp sốt cà chua và sốt mayonnaise béo nhẹ tạo hương vị hài hòa. Lựa chọn lý tưởng cho bữa ăn nhanh vừa ngon vừa tiện lợi.</p><p><strong>Thành phần:</strong> Bột mì, xúc xích, sốt cà chua, sốt mayonnaise, bơ, men nở.</p><p><strong>Bảo quản:</strong> Ngăn mát tủ lạnh 2-8°C, dùng trong 2 ngày, hâm nóng lại trước khi dùng.</p>' WHERE id=15;
UPDATE banh SET mo_ta='<p><strong>Mô tả sản phẩm:</strong> Bánh Tart trái cây kết hợp vỏ tart nướng vàng ươm, giòn rụm thơm bơ với lớp nhân kem custard béo ngậy, mịn màng bên trong. Mặt bánh xếp đầy trái cây tươi theo mùa như dâu tây, kiwi, xoài hoặc việt quất, phủ lớp thạch mỏng giữ độ tươi. Sự đối lập giữa vỏ giòn và trái cây mọng nước mang lại trải nghiệm thanh mát, đầy màu sắc.</p><p><strong>Thành phần:</strong> Bột mì, bơ, trứng, sữa, kem custard, trái cây tươi, thạch.</p><p><strong>Bảo quản:</strong> Ngăn mát tủ lạnh 2-8°C, dùng trong 2 ngày.</p>' WHERE id=17;
UPDATE banh SET mo_ta='<p><strong>Mô tả sản phẩm:</strong> Bánh Burger BBQ kết hợp lớp bánh mì mềm mịn, vàng nhẹ và phần nhân đậm đà bên trong. Thịt nướng BBQ tẩm ướp kỹ, thơm lừng, xen chút ngọt nhẹ của sốt BBQ, ăn cùng rau tươi giòn và sốt béo nhẹ. Chiếc bánh vừa ngon miệng, vừa đủ dinh dưỡng cho bữa ăn nhanh.</p><p><strong>Thành phần:</strong> Bột mì, thịt nướng BBQ, rau tươi, sốt BBQ, bơ, men nở.</p><p><strong>Bảo quản:</strong> Ngăn mát tủ lạnh 2-8°C, dùng trong 2 ngày, hâm nóng lại trước khi dùng.</p>' WHERE id=18;
UPDATE banh SET mo_ta='<p><strong>Mô tả sản phẩm:</strong> Bánh Croissant là dòng bánh mì ngọt cao cấp với lớp vỏ vàng óng, giòn nhẹ và cấu trúc nhiều lớp xếp chồng tinh tế. Từng lớp bánh mỏng tách nhẹ, mềm xốp bên trong, hòa quyện hương bơ thơm ngậy đặc trưng. Có thể dùng kèm mứt trái cây, mật ong hoặc thưởng thức nguyên bản chuẩn vị Pháp.</p><p><strong>Thành phần:</strong> Bột mì, bơ Pháp, trứng, sữa, men nở, đường.</p><p><strong>Bảo quản:</strong> Nơi khô ráo thoáng mát, tránh ánh nắng trực tiếp, hâm nóng nhẹ lại nếu muốn giòn hơn.</p>' WHERE id=20;
UPDATE banh SET mo_ta='<p><strong>Mô tả sản phẩm:</strong> Tiramisu Matcha kết hợp cốt bánh bông lan tươi mềm với lớp kem trứng, đường và phô mai đánh bông mịn màng, xen vị matcha thơm lừng. Bề mặt bánh rắc thêm bột matcha nguyên chất tạo hương vị đặc trưng, hấp dẫn. Bánh dùng lạnh sẽ ngon hơn.</p><p><strong>Thành phần:</strong> Bột mì, trứng, đường, phô mai mascarpone, bột matcha, kem tươi.</p><p><strong>Bảo quản:</strong> Ngăn mát tủ lạnh 2-8°C, dùng trong 4 ngày.</p>' WHERE id=25;
UPDATE banh SET mo_ta='<p><strong>Mô tả sản phẩm:</strong> Bánh Cheesecake Cherry giao thoa vị béo ngậy, chua thanh nhẹ của kem phô mai mịn màng và đế bánh quy bơ thơm giòn. Điểm nhấn là lớp sốt cherry đỏ mọng phủ trên bề mặt, giúp cân bằng vị giác. Trải nghiệm ẩm thực sang trọng, lôi cuốn.</p><p><strong>Thành phần:</strong> Bột bánh quy, bơ, phô mai kem, trứng, cherry, đường.</p><p><strong>Bảo quản:</strong> Ngăn mát tủ lạnh 2-8°C, dùng trong 3-5 ngày.</p>' WHERE id=26;
UPDATE banh SET mo_ta='<p><strong>Mô tả sản phẩm:</strong> Bánh Mochi Dâu tây kết hợp lớp vỏ bột nếp Nhật Bản dẻo mịn, dai nhẹ và nhân đậu đỏ bùi béo, ngọt thanh. Tâm điểm là quả dâu tây tươi mọng, chua ngọt tự nhiên, tạo bùng nổ hương vị khi thưởng thức. Món tráng miệng vừa truyền thống vừa hiện đại, hấp dẫn.</p><p><strong>Thành phần:</strong> Bột nếp, đậu đỏ, dâu tây tươi, đường.</p><p><strong>Bảo quản:</strong> Ngăn mát tủ lạnh 2-8°C, dùng trong 2 ngày.</p>' WHERE id=27;
UPDATE banh SET mo_ta='<p><strong>Mô tả sản phẩm:</strong> Bánh Muffin Cherry kết hợp cốt bánh bơ sữa xốp mịn và lớp kem tươi thanh khiết, điểm xuyết cherry đỏ mọng ngọt lịm. Vị chua nhẹ của sốt cherry ẩn bên trong hòa quyện độ béo ngậy của lớp kem trang trí tỉ mỉ. Mỗi chiếc bánh nhỏ xinh, mang trải nghiệm vị giác đẳng cấp.</p><p><strong>Thành phần:</strong> Bột mì, bơ, trứng, sữa, kem tươi, cherry, đường.</p><p><strong>Bảo quản:</strong> Ngăn mát tủ lạnh 2-8°C, dùng trong 3-5 ngày.</p>' WHERE id=28;
UPDATE banh SET mo_ta='<p><strong>Mô tả sản phẩm:</strong> Bánh Muffin Dâu tây nhỏ xinh với cốt bánh bơ sữa xốp mềm, hương vani dịu nhẹ. Mỗi chiếc phủ lớp kem tươi hoặc kem phô mai hồng nhạt bắt mắt, hòa quyện mứt dâu tây ngọt ngào ẩn bên trong và dâu tây tươi trang trí trên cùng. Vị béo ngậy của kem cân bằng hoàn hảo cùng vị chua thanh tự nhiên.</p><p><strong>Thành phần:</strong> Bột mì, bơ, trứng, sữa, kem tươi, mứt dâu tây, dâu tây tươi.</p><p><strong>Bảo quản:</strong> Ngăn mát tủ lạnh 2-8°C, dùng trong 3-5 ngày.</p>' WHERE id=29;
UPDATE banh SET mo_ta='<p><strong>Mô tả sản phẩm:</strong> Tiramisu truyền thống kết hợp lớp bánh Ladyfingers mềm mại thấm đẫm cà phê espresso đậm đà, xen kẽ kem phô mai Mascarpone béo ngậy, mịn màng. Bề mặt phủ bột cacao nguyên chất, cân bằng hoàn hảo giữa vị đắng nhẹ, ngọt thanh và béo bùi đặc trưng Ý. Bánh dùng lạnh là ngon nhất.</p><p><strong>Thành phần:</strong> Bánh ladyfinger, trứng, cà phê espresso, phô mai mascarpone, bột cacao, đường.</p><p><strong>Bảo quản:</strong> Ngăn mát tủ lạnh 2-8°C, dùng trong 3-5 ngày.</p>' WHERE id=30;
UPDATE banh SET mo_ta='<p><strong>Mô tả sản phẩm:</strong> Bánh Tart có lớp vỏ vàng ươm, giòn rụm, đậm hương vị bơ Pháp. Bên trong là nhân kem trứng custard mềm mịn, tan chảy với vị ngọt thanh và hương vani dịu nhẹ. Kết cấu ngoài giòn trong mềm mang đến cảm giác thích thú cho người yêu bánh nướng truyền thống.</p><p><strong>Thành phần:</strong> Bột mì, bơ Pháp, trứng, sữa, kem custard, đường vani.</p><p><strong>Bảo quản:</strong> Ngăn mát tủ lạnh 2-8°C, dùng trong 2 ngày, có thể hâm nóng nhẹ để vỏ giòn lại.</p>' WHERE id=31;
UPDATE banh SET mo_ta='<p><strong>Mô tả sản phẩm:</strong> Bánh quy mix hạt là món ăn nhẹ giàu dinh dưỡng, kết hợp cốt bánh quy bơ thơm lừng, giòn tan với các loại hạt cao cấp như hạnh nhân, hạt điều, hạt bí và mè đen. Mỗi miếng bánh mang vị bùi béo tự nhiên từ hạt, hòa quyện độ ngọt nhẹ và hương bơ Pháp nồng nàn. Lựa chọn tuyệt vời cho người thích vị nguyên bản, ít ngọt.</p><p><strong>Thành phần:</strong> Bột mì, bơ Pháp, trứng, hạnh nhân, hạt điều, hạt bí, mè đen, đường.</p><p><strong>Bảo quản:</strong> Nơi khô ráo thoáng mát, đựng hộp kín để giữ độ giòn, dùng trong 10 ngày.</p>' WHERE id=32;
UPDATE banh SET mo_ta='<p><strong>Mô tả sản phẩm:</strong> Bánh Muffin hình nhím kết hợp đáng yêu giữa cốt bánh bông lan bơ sữa mềm xốp, ngọt thanh dịu nhẹ và lớp kem béo ngậy trang trí tỉ mỉ. Điểm nhấn độc đáo là lớp gai nhím làm từ hạnh nhân lát giòn rụm bao quanh khuôn mặt nhím bằng kem tươi dễ thương. Món quà tặng tinh tế, phù hợp cho trẻ em và tiệc trà thân mật.</p><p><strong>Thành phần:</strong> Bột mì, bơ, trứng, sữa, kem tươi, hạnh nhân lát, đường.</p><p><strong>Bảo quản:</strong> Ngăn mát tủ lạnh 2-8°C, dùng trong 3 ngày.</p>' WHERE id=33;
UPDATE banh SET mo_ta='<p><strong>Mô tả sản phẩm:</strong> Bánh mì phô mai hải sản kết hợp lớp vỏ bánh vàng ươm, mềm xốp và phần nhân hải sản tươi ngon đầy ắp bên trong. Nhân bánh hòa quyện tôm, hải sản đậm đà cùng phô mai tan chảy béo ngậy. Hương vị hiện đại, thơm nồng mùi bơ sữa, ngọt tự nhiên từ biển cả.</p><p><strong>Thành phần:</strong> Bột mì, tôm, hải sản, phô mai, bơ, trứng, men nở.</p><p><strong>Bảo quản:</strong> Ngăn mát tủ lạnh dùng trong ngày hoặc ngăn đông để bảo quản lâu hơn, hâm nóng trước khi dùng.</p>' WHERE id=34;
UPDATE banh SET mo_ta='<p><strong>Mô tả sản phẩm:</strong> Bánh Muffin Chocolate kết hợp đậm đà cốt bánh cacao xốp mềm, ẩm mịn với lớp kem ganache chocolate béo ngậy phủ trên bề mặt. Vị đắng nhẹ của chocolate nguyên chất hòa quyện độ ngọt thanh của kem tươi, tạo hương vị nồng nàn, lôi cuốn. Bánh thường trang trí thêm vụn chocolate, mang trải nghiệm đa dạng về kết cấu.</p><p><strong>Thành phần:</strong> Bột mì, bơ, trứng, bột cacao, chocolate, kem tươi, đường.</p><p><strong>Bảo quản:</strong> Ngăn mát tủ lạnh 2-8°C, dùng trong 3-5 ngày.</p>' WHERE id=35;
UPDATE banh SET mo_ta='<p><strong>Mô tả sản phẩm:</strong> Bánh Cheesecake Dâu tây kết hợp hoàn hảo đế bánh quy bơ giòn thơm và thân bánh phô mai béo ngậy, mềm mịn như lụa. Vị chua thanh tự nhiên của lớp sốt dâu tây đỏ mọng phủ trên bề mặt cân bằng hoàn hảo với vị béo đặc trưng của phô mai. Trải nghiệm ẩm thực sang trọng, thanh mát, đầy lôi cuốn.</p><p><strong>Thành phần:</strong> Bột bánh quy, bơ, phô mai kem, trứng, dâu tây, đường.</p><p><strong>Bảo quản:</strong> Ngăn mát tủ lạnh 2-8°C, dùng trong 3-5 ngày.</p>' WHERE id=36;
UPDATE banh SET mo_ta='<p><strong>Mô tả sản phẩm:</strong> Bánh kem Oreo Việt quất giao thoa vị ngọt đắng đặc trưng của bánh quy Oreo nghiền vụn và vị chua thanh tươi mát từ mứt việt quất tự nhiên. Lớp kem tươi mềm mịn, béo ngậy đánh bông cùng phô mai, xen kẽ cốt bánh bông lan xốp nhẹ tạo cấu trúc đa tầng thú vị. Bề mặt trang trí Oreo nguyên bản và việt quất mọng nước, hiện đại và lôi cuốn.</p><p><strong>Thành phần:</strong> Bột mì, trứng, bánh quy Oreo, phô mai kem, kem tươi, việt quất, đường.</p><p><strong>Bảo quản:</strong> Ngăn mát tủ lạnh 2-8°C, dùng trong 3-5 ngày.</p>' WHERE id=37;
UPDATE banh SET mo_ta='<p><strong>Mô tả sản phẩm:</strong> Bánh kem Dâu tây kết hợp ngọt ngào giữa cốt bánh bông lan vani thơm bơ và lớp kem tươi trắng muốt, mịn màng. Điểm nhấn là những lát dâu tây tươi mọng, chua ngọt thanh khiết đan xen giữa các lớp kem, cân bằng vị béo. Hương thơm tự nhiên cùng sắc đỏ bắt mắt tạo nên món bánh tinh tế, tràn đầy sức sống.</p><p><strong>Thành phần:</strong> Bột mì, trứng, bơ, kem tươi, dâu tây tươi, đường.</p><p><strong>Bảo quản:</strong> Ngăn mát tủ lạnh 2-8°C, dùng trong 3-5 ngày.</p>' WHERE id=38;
UPDATE banh SET mo_ta='<p><strong>Mô tả sản phẩm:</strong> Bánh kem Phô mai Bắp kết hợp độc đáo vị béo mịn của kem phô mai và vị ngọt thanh tự nhiên từ hạt bắp. Cốt bánh bông lan mềm xốp xen kẽ lớp kem phô mai thơm ngậy, hòa quyện hạt bắp vàng giòn nhẹ, tạo kết cấu thú vị. Vị béo, ngọt và bùi của bắp khiến chiếc bánh mới lạ nhưng vẫn dễ ăn.</p><p><strong>Thành phần:</strong> Bột mì, trứng, phô mai kem, kem tươi, bắp ngọt, đường.</p><p><strong>Bảo quản:</strong> Ngăn mát tủ lạnh 2-8°C, dùng trong 3-5 ngày.</p>' WHERE id=39;
UPDATE banh SET mo_ta='<p><strong>Mô tả sản phẩm:</strong> Bánh kem Valentine là món quà ngọt ngào cho dịp đặc biệt, thiết kế tinh tế với gam màu lãng mạn như đỏ, hồng hoặc trắng. Cốt bánh bông lan mềm mịn kết hợp lớp kem tươi béo nhẹ, trang trí họa tiết trái tim, chocolate mang thông điệp yêu thương. Hương vị ngọt dịu, không gắt, phù hợp chia sẻ khoảnh khắc ý nghĩa.</p><p><strong>Thành phần:</strong> Bột mì, trứng, kem tươi, chocolate, phẩm màu thực phẩm, đường.</p><p><strong>Bảo quản:</strong> Ngăn mát tủ lạnh 2-8°C, dùng trong 3-5 ngày.</p>' WHERE id=40;
UPDATE banh SET mo_ta='<p><strong>Mô tả sản phẩm:</strong> Bánh mì hoa Cúc là dòng bánh ngọt cao cấp với kết cấu mềm xốp, dai nhẹ đặc trưng và hương thơm quyến rũ từ bơ, sữa và trứng. Bánh tạo hình đan xen đẹp mắt, lớp vỏ ngoài vàng óng. Khi thưởng thức, bánh có vị ngọt thanh, béo nhẹ, thớ bánh tơi mịn, phù hợp cho bữa sáng hoặc dùng kèm trà cà phê.</p><p><strong>Thành phần:</strong> Bột mì, bơ, sữa, trứng, đường.</p><p><strong>Bảo quản:</strong> Nơi khô ráo thoáng mát, có thể để ngăn mát tủ lạnh để dùng lâu hơn.</p>' WHERE id=41;
UPDATE banh SET mo_ta='<p><strong>Mô tả sản phẩm:</strong> Bánh mì kem phô mai tan chảy có lớp vỏ ngoài mềm mịn, phủ nhẹ bột sữa thơm béo. Bên trong là nhân kem phô mai sánh mịn, béo ngậy, tan chảy khi cắn vào, mang cảm giác rất đã miệng. Sự kết hợp giữa lớp bánh tơi xốp và nhân mịn mượt tạo hương vị ngọt dịu, béo hài hòa.</p><p><strong>Thành phần:</strong> Bột mì, bơ, sữa, phô mai kem, bột sữa, trứng, đường.</p><p><strong>Bảo quản:</strong> Ngăn mát tủ lạnh 2-8°C, dùng trong 2 ngày.</p>' WHERE id=42;
UPDATE banh SET mo_ta='<p><strong>Mô tả sản phẩm:</strong> Bánh mì Sandwich mềm mịn, kết cấu xốp nhẹ và vị ngọt dịu dễ ăn. Lớp vỏ mỏng, ruột bánh trắng mịn, linh hoạt khi kết hợp cùng nhiều loại nhân như trứng, thịt nguội, phô mai hoặc mứt trái cây. Lựa chọn hoàn hảo cho bữa sáng nhanh gọn, tiện lợi mà vẫn đủ dinh dưỡng.</p><p><strong>Thành phần:</strong> Bột mì, sữa, đường, men nở, bơ.</p><p><strong>Bảo quản:</strong> Nơi khô ráo thoáng mát, có thể để ngăn mát tủ lạnh để dùng lâu hơn, nướng nhẹ lại cho giòn.</p>' WHERE id=43;
UPDATE banh SET mo_ta='<p><strong>Mô tả sản phẩm:</strong> Bánh mì Việt Nam là loại bánh truyền thống với lớp vỏ ngoài vàng giòn rụm, ruột bánh mềm xốp, nhẹ và thoáng. Khi thưởng thức, độ giòn đặc trưng hòa quyện cùng phần ruột dai nhẹ, mang cảm giác rất đã miệng. Thường dùng kèm nhiều loại nhân như thịt, pate, rau và đồ chua.</p><p><strong>Thành phần:</strong> Bột mì, men nở, muối, đường, nước.</p><p><strong>Bảo quản:</strong> Nơi khô ráo thoáng mát, dùng trong ngày, nướng lại cho giòn.</p>' WHERE id=44;
UPDATE banh SET mo_ta='<p><strong>Mô tả sản phẩm:</strong> Bánh Crepe Sầu riêng là món tráng miệng hấp dẫn với lớp vỏ crepe mỏng mềm, mịn màng ôm trọn phần nhân bên trong. Nhân bánh kết hợp kem tươi béo nhẹ và sầu riêng chín thơm lừng, mang hương vị đặc trưng, ngọt ngào đậm đà. Lớp vỏ mềm tan cùng nhân sánh mịn tạo cảm giác cuốn hút cho tín đồ yêu sầu riêng.</p><p><strong>Thành phần:</strong> Bột mì, trứng, sữa, kem tươi, sầu riêng, đường.</p><p><strong>Bảo quản:</strong> Ngăn mát tủ lạnh 2-8°C, dùng trong 2 ngày.</p>' WHERE id=46;
UPDATE banh SET mo_ta='<p><strong>Mô tả sản phẩm:</strong> Bánh kem Xoài kết hợp tươi mát giữa cốt bánh bông lan mềm mịn và lớp kem tươi béo nhẹ, hòa quyện xoài chín vàng ngọt lịm. Những miếng xoài tươi xen kẽ giữa các lớp bánh giúp cân bằng vị béo, mang cảm giác thanh nhẹ, không ngấy. Hương thơm tự nhiên cùng màu sắc bắt mắt tạo nên chiếc bánh vừa ngon vừa hấp dẫn.</p><p><strong>Thành phần:</strong> Bột mì, trứng, kem tươi, xoài chín, đường.</p><p><strong>Bảo quản:</strong> Ngăn mát tủ lạnh 2-8°C, dùng trong 3-5 ngày.</p>' WHERE id=47;
UPDATE banh SET mo_ta='<p><strong>Mô tả sản phẩm:</strong> Bánh kem Trái cây Mix hòa quyện tươi mát giữa cốt bánh bông lan mềm mịn và lớp kem tươi béo nhẹ. Bánh phủ và trang trí nhiều loại trái cây tươi như dâu, kiwi, nho, xoài, mang hương vị đa dạng, chua ngọt hài hòa, không ngấy. Màu sắc rực rỡ, hương thơm tự nhiên phù hợp cho sinh nhật, liên hoan hay tiệc nhẹ.</p><p><strong>Thành phần:</strong> Bột mì, trứng, kem tươi, trái cây tươi mix, đường.</p><p><strong>Bảo quản:</strong> Ngăn mát tủ lạnh 2-8°C, dùng trong 3-5 ngày.</p>' WHERE id=48;
UPDATE banh SET mo_ta='<p><strong>Mô tả sản phẩm:</strong> Bánh kem hình hoa mang vẻ đẹp tinh tế với lớp kem tươi tạo hình những bông hoa mềm mại, sống động. Cốt bánh bông lan mềm xốp kết hợp lớp kem béo nhẹ, ngọt dịu tạo hương vị hài hòa, dễ ăn. Thiết kế hoa trang nhã, màu sắc nhẹ nhàng, phù hợp làm quà tặng ý nghĩa.</p><p><strong>Thành phần:</strong> Bột mì, trứng, kem tươi, đường, phẩm màu thực phẩm.</p><p><strong>Bảo quản:</strong> Ngăn mát tủ lạnh 2-8°C, dùng trong 3-5 ngày.</p>' WHERE id=49;
UPDATE banh SET mo_ta='<p><strong>Mô tả sản phẩm:</strong> Bánh su kem là món bánh ngọt hấp dẫn với lớp vỏ mỏng, mềm nhẹ và hơi dai đặc trưng. Bên trong là nhân kem sánh mịn, béo ngậy, có thể là kem sữa hoặc custard, mang cảm giác mát lạnh, tan ngay trong miệng. Sự kết hợp giữa vỏ nhẹ và nhân kem đậm đà tạo hương vị hài hòa, dễ gây thương nhớ.</p><p><strong>Thành phần:</strong> Bột mì, bơ, trứng, sữa, kem custard, đường.</p><p><strong>Bảo quản:</strong> Ngăn mát tủ lạnh 2-8°C, dùng trong 2 ngày.</p>' WHERE id=50;
UPDATE banh SET mo_ta='<p><strong>Mô tả sản phẩm:</strong> Cheesecake Việt quất là món bánh cao cấp với đế bánh quy giòn nhẹ kết hợp lớp kem phô mai mềm mịn, béo ngậy. Sốt việt quất phủ bên trên có vị chua ngọt thanh mát, cân bằng độ béo của phô mai, tạo hương vị hài hòa. Màu tím đỏ bắt mắt cùng hương thơm đặc trưng khiến chiếc bánh hấp dẫn ngay từ cái nhìn đầu tiên.</p><p><strong>Thành phần:</strong> Bột bánh quy, bơ, phô mai kem, trứng, việt quất, đường.</p><p><strong>Bảo quản:</strong> Ngăn mát tủ lạnh 2-8°C, dùng trong 3-5 ngày.</p>' WHERE id=51;
UPDATE banh SET mo_ta='<p><strong>Mô tả sản phẩm:</strong> Cheesecake Chanh dây kết hợp hoàn hảo giữa đế bánh quy giòn nhẹ và lớp kem phô mai mềm mịn, béo ngậy. Điểm nhấn là vị chanh dây tươi thanh mát, chua nhẹ hòa quyện vị béo của phô mai, tạo tổng thể hương vị cân bằng, không ngấy. Hương thơm dịu nhẹ mang đến trải nghiệm tráng miệng tươi mới.</p><p><strong>Thành phần:</strong> Bột bánh quy, bơ, phô mai kem, trứng, chanh dây, đường.</p><p><strong>Bảo quản:</strong> Ngăn mát tủ lạnh 2-8°C, dùng trong 3-5 ngày.</p>' WHERE id=52;
UPDATE banh SET mo_ta='<p><strong>Mô tả sản phẩm:</strong> Cheesecake Caramel hòa quyện tinh tế giữa đế bánh quy giòn nhẹ và lớp kem phô mai mềm mịn, béo ngậy. Điểm nhấn là lớp sốt caramel óng mượt với vị ngọt đậm đà, thoảng chút đắng nhẹ đặc trưng, cân bằng hoàn hảo vị béo của phô mai. Hương thơm quyến rũ cùng kết cấu mịn mượt mang đến trải nghiệm tráng miệng sang trọng.</p><p><strong>Thành phần:</strong> Bột bánh quy, bơ, phô mai kem, trứng, caramel, đường.</p><p><strong>Bảo quản:</strong> Ngăn mát tủ lạnh 2-8°C, dùng trong 3-5 ngày.</p>' WHERE id=53;
UPDATE banh SET mo_ta='<p><strong>Mô tả sản phẩm:</strong> Cupcake Red Velvet với lớp kem cheese frosting béo ngậy, cốt bánh đỏ mềm mịn. Thích hợp làm quà tặng, tiệc sinh nhật hoặc thưởng thức cùng trà chiều.</p><p><strong>Thành phần:</strong> Bột mì, bơ, trứng, cacao, cream cheese, đường, phẩm màu thực phẩm.</p><p><strong>Bảo quản:</strong> Ngăn mát tủ lạnh 2-8°C, dùng trong 3 ngày.</p>' WHERE id=54;
UPDATE banh SET mo_ta='<p><strong>Mô tả sản phẩm:</strong> Cupcake chocolate đậm đà với lớp ganache chocolate Bỉ bóng mượt phủ trên cốt bánh chocolate xốp mềm. Phù hợp mọi lứa tuổi.</p><p><strong>Thành phần:</strong> Bột mì, bơ, trứng, chocolate đen 70%, cacao, đường.</p><p><strong>Bảo quản:</strong> Ngăn mát tủ lạnh 2-8°C, dùng trong 3 ngày.</p>' WHERE id=55;
UPDATE banh SET mo_ta='<p><strong>Mô tả sản phẩm:</strong> Cupcake vani cổ điển với lớp buttercream vani mịn màng, cốt bánh bơ thơm lừng. Hương vị nhẹ nhàng, thanh ngọt, phù hợp làm quà hoặc trang trí tiệc.</p><p><strong>Thành phần:</strong> Bột mì, bơ, trứng, tinh chất vani, đường, kem tươi.</p><p><strong>Bảo quản:</strong> Ngăn mát tủ lạnh 2-8°C, dùng trong 3 ngày.</p>' WHERE id=56;
UPDATE banh SET mo_ta='<p><strong>Mô tả sản phẩm:</strong> Hộp 6 viên macaron Pháp với các vị: chocolate, matcha, dâu tây, chanh, vani và caramel muối. Vỏ giòn mỏng, nhân ganache mềm mịn tan trên đầu lưỡi. Đóng hộp sang trọng, lý tưởng làm quà tặng.</p><p><strong>Thành phần:</strong> Bột hạnh nhân, đường bột, lòng trắng trứng, chocolate, matcha, bơ, kem tươi.</p><p><strong>Bảo quản:</strong> Ngăn mát tủ lạnh 2-8°C, dùng trong 5 ngày.</p>' WHERE id=57;
UPDATE banh SET mo_ta='<p><strong>Mô tả sản phẩm:</strong> Mousse chocolate Bỉ cao cấp với kết cấu mềm mịn như mây, vị đắng nhẹ hòa quyện cùng vị ngọt thanh. Lớp đáy biscuit giòn tạo điểm nhấn kết cấu. Ít ngọt theo xu hướng healthy.</p><p><strong>Thành phần:</strong> Chocolate đen 70%, kem tươi, trứng, gelatin, bơ, biscuit.</p><p><strong>Bảo quản:</strong> Ngăn mát tủ lạnh 2-8°C, dùng trong 3 ngày.</p>' WHERE id=58;
UPDATE banh SET mo_ta='<p><strong>Mô tả sản phẩm:</strong> Mousse chanh dây tươi mát với vị chua ngọt cân bằng hoàn hảo. Lớp mousse mềm mịn kết hợp cùng lớp jelly chanh dây bên trên và đáy biscuit giòn. Giải nhiệt tuyệt vời cho mùa hè.</p><p><strong>Thành phần:</strong> Chanh dây tươi, kem tươi, đường, gelatin, bơ, biscuit.</p><p><strong>Bảo quản:</strong> Ngăn mát tủ lạnh 2-8°C, dùng trong 3 ngày.</p>' WHERE id=59;
UPDATE banh SET mo_ta='<p><strong>Mô tả sản phẩm:</strong> Brownie chocolate đậm đà kiểu Mỹ, bên ngoài hơi giòn, bên trong ẩm mềm fudgy. Sử dụng chocolate đen cao cấp và bơ Pháp. Phần trên rắc thêm hạt óc chó rang thơm bùi.</p><p><strong>Thành phần:</strong> Chocolate đen, bơ, trứng, đường, bột mì, hạt óc chó.</p><p><strong>Bảo quản:</strong> Nhiệt độ phòng 1-2 ngày, tủ lạnh 5 ngày.</p>' WHERE id=60;
UPDATE banh SET mo_ta='<p><strong>Mô tả sản phẩm:</strong> Chiffon cake kiểu Nhật Bản, nhẹ xốp như bông mây với hương vani tự nhiên. Ít đường, ít dầu, phù hợp người thích vị thanh nhẹ. Size 18cm thích hợp cho 4-6 người. Có thể kèm kem tươi và trái cây theo yêu cầu.</p><p><strong>Thành phần:</strong> Bột mì, trứng, dầu thực vật, đường, tinh chất vani.</p><p><strong>Bảo quản:</strong> Ngăn mát tủ lạnh 2-8°C, dùng trong 3 ngày.</p>' WHERE id=61;
UPDATE banh SET mo_ta='<p><strong>Mô tả sản phẩm:</strong> Éclair Pháp cổ điển với vỏ choux giòn xốp, nhân kem custard vani béo ngậy, phủ lớp ganache chocolate bóng mượt bên trên. Thưởng thức ngon nhất khi mới làm.</p><p><strong>Thành phần:</strong> Bột mì, bơ, trứng, sữa, chocolate, kem tươi, đường, vani.</p><p><strong>Bảo quản:</strong> Ngăn mát tủ lạnh 2-8°C, dùng trong 2 ngày.</p>' WHERE id=62;
UPDATE banh SET mo_ta='<p><strong>Mô tả sản phẩm:</strong> Mille Crepe với hơn 20 lớp crepe mỏng mịn xen kẽ lớp kem tươi matcha Nhật Bản. Vị trà xanh đắng nhẹ hòa quyện cùng kem ngọt thanh. Size 16cm cho 4-6 người. Top trending 2025-2026.</p><p><strong>Thành phần:</strong> Bột mì, trứng, sữa, bơ, kem tươi, bột matcha Uji.</p><p><strong>Bảo quản:</strong> Ngăn mát tủ lạnh 2-8°C, dùng trong 3 ngày.</p>' WHERE id=63;
UPDATE banh SET mo_ta='<p><strong>Mô tả sản phẩm:</strong> Pain au Chocolat Pháp với lớp bột ngàn lớp giòn xốp bọc hai thanh chocolate đen bên trong. Nướng vàng thơm mỗi sáng, thưởng thức khi còn ấm là ngon nhất. Kết hợp hoàn hảo cùng cà phê.</p><p><strong>Thành phần:</strong> Bột mì, bơ Pháp, chocolate đen, trứng, sữa, men, đường.</p><p><strong>Bảo quản:</strong> Nhiệt độ phòng trong ngày, hâm nóng lại 180°C/3 phút.</p>' WHERE id=64;
UPDATE banh SET mo_ta='<p><strong>Mô tả sản phẩm:</strong> Bánh Danish giòn xốp với lớp kem custard vani và trái cây tươi theo mùa (dâu tây, việt quất, kiwi). Lớp vỏ nhiều lớp giòn tan, phủ mứt bóng lên trên. Lý tưởng cho bữa sáng hoặc trà chiều.</p><p><strong>Thành phần:</strong> Bột mì, bơ, trứng, sữa, kem custard, trái cây tươi.</p><p><strong>Bảo quản:</strong> Dùng trong ngày để giữ độ giòn.</p>' WHERE id=65;
UPDATE banh SET mo_ta='<p><strong>Mô tả sản phẩm:</strong> Hộp 4 donut mềm xốp với các vị: đường phủ, chocolate, dâu tây và matcha. Vỏ ngoài phủ lớp topping rực rỡ, bên trong mềm nhẹ. Phù hợp chia sẻ cùng gia đình hoặc bạn bè.</p><p><strong>Thành phần:</strong> Bột mì, bơ, trứng, sữa, men, đường, chocolate, topping các vị.</p><p><strong>Bảo quản:</strong> Nhiệt độ phòng trong ngày, tủ lạnh 2 ngày.</p>' WHERE id=66;
UPDATE banh SET mo_ta='<p><strong>Mô tả sản phẩm:</strong> Panna Cotta Ý truyền thống với kết cấu mềm mượt như lụa, hương vani Madagascar. Phủ lớp coulis dâu tây tươi hoặc caramel tùy chọn. Tráng miệng thanh mát, nhẹ nhàng.</p><p><strong>Thành phần:</strong> Kem tươi, sữa, đường, gelatin, vani, dâu tây.</p><p><strong>Bảo quản:</strong> Ngăn mát tủ lạnh 2-8°C, dùng trong 3 ngày.</p>' WHERE id=67;
UPDATE banh SET mo_ta='<p><strong>Mô tả sản phẩm:</strong> Bánh flan caramel truyền thống Việt Nam, mềm mịn thơm béo mùi trứng và sữa. Lớp caramel đắng nhẹ bên dưới cân bằng vị ngọt. Ăn lạnh hoặc thêm đá đều ngon. Món tráng miệng quen thuộc mọi nhà.</p><p><strong>Thành phần:</strong> Trứng, sữa tươi, sữa đặc, đường, vani.</p><p><strong>Bảo quản:</strong> Ngăn mát tủ lạnh 2-8°C, dùng trong 3 ngày.</p>' WHERE id=68;
UPDATE banh SET mo_ta='<p><strong>Mô tả sản phẩm:</strong> Hộp 12 cookie bơ thơm giòn với hai vị: bơ truyền thống và chocolate chip. Sử dụng bơ Pháp và chocolate chip Bỉ. Đóng hộp đẹp, thích hợp làm quà biếu, quà tặng hoặc ăn vặt hàng ngày.</p><p><strong>Thành phần:</strong> Bột mì, bơ Pháp, đường nâu, trứng, chocolate chip, vani, muối.</p><p><strong>Bảo quản:</strong> Nhiệt độ phòng mát 7-10 ngày, hộp kín.</p>' WHERE id=69;
UPDATE banh SET mo_ta='<p><strong>Mô tả sản phẩm:</strong> Bánh patê sô truyền thống Việt Nam với lớp vỏ puff pastry giòn ngàn lớp, nhân patê gan heo thơm béo kết hợp thịt heo xay. Nướng vàng giòn mỗi ngày. Ăn sáng hoặc ăn vặt đều phù hợp.</p><p><strong>Thành phần:</strong> Bột mì, bơ, trứng, patê gan, thịt heo, hành, tiêu, nước mắm.</p><p><strong>Bảo quản:</strong> Nhiệt độ phòng trong ngày, hâm nóng 180°C/5 phút.</p>' WHERE id=70;
UPDATE banh SET mo_ta='<p><strong>Mô tả sản phẩm:</strong> Quiche Lorraine Pháp với vỏ tart bơ giòn, nhân trứng kem béo ngậy kết hợp thịt xông khói, phô mai Gruyère và hành tây caramel. Size 12cm cho 1-2 người. Phù hợp bữa brunch hoặc ăn nhẹ.</p><p><strong>Thành phần:</strong> Bột mì, bơ, trứng, kem tươi, thịt xông khói, phô mai Gruyère, hành tây.</p><p><strong>Bảo quản:</strong> Ngăn mát tủ lạnh 2-8°C, dùng trong 2 ngày. Hâm nóng 180°C/5 phút.</p>' WHERE id=71;
UPDATE banh SET mo_ta='<p><strong>Mô tả sản phẩm:</strong> Bánh bao truyền thống với vỏ bột mềm trắng mịn, nhân thịt heo xay kết hợp trứng cút, nấm mèo và miến. Hấp nóng tại tiệm mỗi ngày. Bữa sáng tiện lợi, no lâu.</p><p><strong>Thành phần:</strong> Bột mì, thịt heo, trứng cút, nấm mèo, miến, hành, tiêu.</p><p><strong>Bảo quản:</strong> Ngăn mát 2 ngày, ngăn đông 2 tuần. Hấp lại 10 phút trước khi ăn.</p>' WHERE id=72;
UPDATE banh SET mo_ta='<p><strong>Mô tả sản phẩm:</strong> Puff pastry cuộn xúc xích Đức nguyên cây, vỏ bột ngàn lớp giòn rụm bọc xúc xích thịt heo thơm ngon. Nướng vàng giòn, phủ mè trắng bên ngoài. Ăn nóng là ngon nhất, phù hợp ăn sáng hoặc ăn vặt.</p><p><strong>Thành phần:</strong> Bột mì, bơ, xúc xích Đức, trứng, mè trắng.</p><p><strong>Bảo quản:</strong> Nhiệt độ phòng trong ngày, hâm nóng 180°C/5 phút.</p>' WHERE id=73;

-- === Refined allergen tags ===

UPDATE banh SET co_trung=1, co_sua=1, co_gluten=1, co_hat=0 WHERE id=2; -- Bánh Kem Chocolate
UPDATE banh SET co_trung=1, co_sua=1, co_gluten=1, co_hat=0 WHERE id=3; -- Bánh kem Cherry
UPDATE banh SET co_trung=0, co_sua=1, co_gluten=1, co_hat=0 WHERE id=13; -- Bánh mì bơ tỏi
UPDATE banh SET co_trung=1, co_sua=1, co_gluten=1, co_hat=0 WHERE id=14; -- Bánh bông lan trứng muối
UPDATE banh SET co_trung=1, co_sua=1, co_gluten=1, co_hat=0 WHERE id=15; -- Bánh mì Hotdog
UPDATE banh SET co_trung=1, co_sua=1, co_gluten=1, co_hat=0 WHERE id=17; -- Bánh Tart trái cây
UPDATE banh SET co_trung=1, co_sua=1, co_gluten=1, co_hat=0 WHERE id=18; -- Bánh Burger BBQ
UPDATE banh SET co_trung=1, co_sua=1, co_gluten=1, co_hat=0 WHERE id=20; -- Bánh Croissant
UPDATE banh SET co_trung=1, co_sua=1, co_gluten=1, co_hat=0 WHERE id=25; -- Tiramisu Matcha
UPDATE banh SET co_trung=1, co_sua=1, co_gluten=1, co_hat=0 WHERE id=26; -- Bánh Cheesecake Cherry
UPDATE banh SET co_trung=0, co_sua=0, co_gluten=0, co_hat=0 WHERE id=27; -- Bánh Mochi Dâu tây
UPDATE banh SET co_trung=1, co_sua=1, co_gluten=1, co_hat=0 WHERE id=28; -- Bánh Muffin Cherry
UPDATE banh SET co_trung=1, co_sua=1, co_gluten=1, co_hat=0 WHERE id=29; -- Bánh Muffin Dâu tây
UPDATE banh SET co_trung=1, co_sua=1, co_gluten=1, co_hat=0 WHERE id=30; -- Tiramisu truyền thống
UPDATE banh SET co_trung=1, co_sua=1, co_gluten=1, co_hat=0 WHERE id=31; -- Bánh Tart
UPDATE banh SET co_trung=1, co_sua=1, co_gluten=1, co_hat=1 WHERE id=32; -- Bánh Quy mix hạt
UPDATE banh SET co_trung=1, co_sua=1, co_gluten=1, co_hat=1 WHERE id=33; -- Bánh Muffin hình nhím
UPDATE banh SET co_trung=1, co_sua=1, co_gluten=1, co_hat=0 WHERE id=34; -- Bánh mì phomai hải sản
UPDATE banh SET co_trung=1, co_sua=1, co_gluten=1, co_hat=0 WHERE id=35; -- Bánh Muffin Chocolate
UPDATE banh SET co_trung=1, co_sua=1, co_gluten=1, co_hat=0 WHERE id=36; -- Bánh Cheesecake Dâu tây
UPDATE banh SET co_trung=1, co_sua=1, co_gluten=1, co_hat=0 WHERE id=37; -- Bánh kem Oreo Việt quất
UPDATE banh SET co_trung=1, co_sua=1, co_gluten=1, co_hat=0 WHERE id=38; -- Bánh kem Dâu tây
UPDATE banh SET co_trung=1, co_sua=1, co_gluten=1, co_hat=0 WHERE id=39; -- Bánh kem Phomai Bắp
UPDATE banh SET co_trung=1, co_sua=1, co_gluten=1, co_hat=0 WHERE id=40; -- Bánh kem Valentine
UPDATE banh SET co_trung=1, co_sua=1, co_gluten=1, co_hat=0 WHERE id=41; -- Bánh mì hoa Cúc
UPDATE banh SET co_trung=1, co_sua=1, co_gluten=1, co_hat=0 WHERE id=42; -- Bánh mì kem phô mai
UPDATE banh SET co_trung=0, co_sua=1, co_gluten=1, co_hat=0 WHERE id=43; -- Bánh mì Sandwich
UPDATE banh SET co_trung=0, co_sua=0, co_gluten=1, co_hat=0 WHERE id=44; -- Bánh mì Việt Nam
UPDATE banh SET co_trung=1, co_sua=1, co_gluten=1, co_hat=0 WHERE id=46; -- Bánh Crepe Sầu riêng
UPDATE banh SET co_trung=1, co_sua=1, co_gluten=1, co_hat=0 WHERE id=47; -- Bánh kem Xoài
UPDATE banh SET co_trung=1, co_sua=1, co_gluten=1, co_hat=0 WHERE id=48; -- Bánh kem Trái cây Mix
UPDATE banh SET co_trung=1, co_sua=1, co_gluten=1, co_hat=0 WHERE id=49; -- Bánh kem hình hoa
UPDATE banh SET co_trung=1, co_sua=1, co_gluten=1, co_hat=0 WHERE id=50; -- Bánh su kem
UPDATE banh SET co_trung=1, co_sua=1, co_gluten=1, co_hat=0 WHERE id=51; -- Cheesecake Việt quất
UPDATE banh SET co_trung=1, co_sua=1, co_gluten=1, co_hat=0 WHERE id=52; -- Cheesecake Chanh dây
UPDATE banh SET co_trung=1, co_sua=1, co_gluten=1, co_hat=0 WHERE id=53; -- Bánh Cheesecake Caramel
UPDATE banh SET co_trung=1, co_sua=1, co_gluten=1, co_hat=0 WHERE id=54; -- Cupcake Red Velvet
UPDATE banh SET co_trung=1, co_sua=1, co_gluten=1, co_hat=0 WHERE id=55; -- Cupcake Chocolate
UPDATE banh SET co_trung=1, co_sua=1, co_gluten=1, co_hat=0 WHERE id=56; -- Cupcake Vani
UPDATE banh SET co_trung=1, co_sua=1, co_gluten=0, co_hat=1 WHERE id=57; -- Macaron hộp 6 vị
UPDATE banh SET co_trung=1, co_sua=1, co_gluten=1, co_hat=0 WHERE id=58; -- Mousse Chocolate
UPDATE banh SET co_trung=0, co_sua=1, co_gluten=1, co_hat=0 WHERE id=59; -- Mousse Chanh dây
UPDATE banh SET co_trung=1, co_sua=1, co_gluten=1, co_hat=1 WHERE id=60; -- Brownie Chocolate
UPDATE banh SET co_trung=1, co_sua=0, co_gluten=1, co_hat=0 WHERE id=61; -- Chiffon cake Vani
UPDATE banh SET co_trung=1, co_sua=1, co_gluten=1, co_hat=0 WHERE id=62; -- Éclair Chocolate
UPDATE banh SET co_trung=1, co_sua=1, co_gluten=1, co_hat=0 WHERE id=63; -- Mille Crepe Matcha
UPDATE banh SET co_trung=1, co_sua=1, co_gluten=1, co_hat=0 WHERE id=64; -- Pain au Chocolat
UPDATE banh SET co_trung=1, co_sua=1, co_gluten=1, co_hat=0 WHERE id=65; -- Danish Trái cây
UPDATE banh SET co_trung=1, co_sua=1, co_gluten=1, co_hat=0 WHERE id=66; -- Donut hộp 4 chiếc
UPDATE banh SET co_trung=0, co_sua=1, co_gluten=0, co_hat=0 WHERE id=67; -- Panna Cotta Vani
UPDATE banh SET co_trung=1, co_sua=1, co_gluten=0, co_hat=0 WHERE id=68; -- Bánh Flan Caramel
UPDATE banh SET co_trung=1, co_sua=1, co_gluten=1, co_hat=0 WHERE id=69; -- Cookie Bơ hộp 12
UPDATE banh SET co_trung=1, co_sua=1, co_gluten=1, co_hat=0 WHERE id=70; -- Bánh Patê Sô (puff pastry egg-wash)
UPDATE banh SET co_trung=1, co_sua=1, co_gluten=1, co_hat=0 WHERE id=71; -- Quiche Lorraine
UPDATE banh SET co_trung=1, co_sua=0, co_gluten=1, co_hat=0 WHERE id=72; -- Bánh Bao nhân thịt
UPDATE banh SET co_trung=1, co_sua=1, co_gluten=1, co_hat=0 WHERE id=73; -- Puff Pastry Xúc xích
